[package]
name = "puzzle_geometry"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
phf = { version = "0.11.3", features = ["macros"] }
nalgebra = "0.33"
thiserror = "2.0"
itertools = "0.13"
