[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
qter_core = { path = "../qter_core" }
internment = { version = "0.8", features = [ "arc" ] }
compiler = { path = "../compiler" }

[lints]
workspace = true
