[package]
name = "cycle_combination_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
integer-partitions = "0.1.1"
memoize = "0.4.2"
pareto_front = "1.0.1"
puzzle_geometry = { version = "0.1.0", path = "../puzzle_geometry" }
qter_core = { version = "0.1.0", path = "../qter_core" }
rstest = "0.24.0"

[lints]
workspace = true

[features]
avx512vl = []
avx512vbmi = []
