[package]
name = "qter_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bnum = "0.12"
itertools = "0.14"
internment = { version = "0.8", features = [ "arc" ] }
pog_ans = { path = "../pog_ans" }
ariadne = "0.5"

[lints]
workspace = true
