name: Deploy Qter site

on:
  push:
    branches:
      - main
    paths:
      - media/paper/**
      - media/www/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  render-paper:
    name: Render paper PDF
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Typst
        uses: typst-community/setup-typst@v4

      - name: Compile document
        run: typst compile media/paper/paper.typ

      - name: Copy paper to web root
        run: ln media/paper/paper.pdf media/www/paper.pdf

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: media/www

  deploy:
    name: Deploy site
    needs: render-paper
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
