name: Render Typst
on:
  push:
    paths:
      - media/paper/**
  workflow_dispatch:
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - name: Render Qter paper
        run: typst compile paper.typ paper.pdf
        working-directory: media/paper
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: media/paper/paper.pdf
